### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by nilesh121** [AkshayDigheGithub/wl#2]
When run npm start after npm install getting error Cannot read property 'apply' of undefined

/wl-master/node_modules/redux/es/redux.js:600
  597 | 
  598 |   return funcs.reduce(function (a, b) {
  599 |     return function () {
> 600 |       return a(b.apply(void 0, arguments));
  601 |     };
  602 |   });
  603 | }

**Comment by AkshayDigheGithub** [comment]
This issue resolved now,  this all happens because of maybe **Dev Tool Extension** not installed on your browser, now this condition handled successfully. Make it resolved.
Dev Tool Extension  for you will get here [Click here](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)
